# Generated by Django 3.1.1 on 2020-10-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_customer', models.BooleanField(default=True, verbose_name='customer status')),
                ('coin', models.IntegerField(default=0, verbose_name='total coin')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pricesetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('price', models.IntegerField(verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='uploads/img/')),
                ('title', models.CharField(default=None, max_length=150, verbose_name='title')),
                ('description', models.CharField(default=None, max_length=500, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='veriation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=50, verbose_name='passcode1')),
                ('price', models.IntegerField(verbose_name='price3')),
                ('expire_status', models.BooleanField(default=True, verbose_name='expire_status')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veriation', to='API.product')),
            ],
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_product', to='API.veriation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_account', to='API.account')),
            ],
        ),
    ]
